#!/usr/bin/env node
// Fills the test gaps a skill has: for every doer artifact and every deterministic
// module that is missing an accuracy, edge-case, or performance test, generate one.
// (Interpreters owe structural evals, not the three-kind regime — they never gap here.)
//
//   npm run test:new -- <skill>          # interactive: confirms each gap, then writes
//   npm run test:new -- <skill> --yes    # write everything missing, no questions
//   npm run test:new                     # report gaps across every skill
//
// Generated tests are scaffolds with real assertions in them — they run, and they
// fail honestly when the code is wrong. Replace the placeholder expectations with
// the real ones; that is the part only the author can do.
import fs from 'node:fs';
import path from 'node:path';
import { Prompter } from './lib/prompt.mjs';
import { coverageGaps, useCaseOf } from './lib/roles.mjs';
import { pythonModules } from './lib/python.mjs';
import * as T from './lib/templates.mjs';
import { REPO_ROOT, discoverSkills, loadCases, loadConfig } from './lib/skills.mjs';
import { bold, dim, green, yellow } from './lib/report.mjs';

/** One Python test file per missing kind. */
function pythonTestFor(config, skill, kind) {
  const useCase = useCaseOf(config, skill.name);
  const module = T.moduleNameFor(useCase);
  const file = path.join(skill.dir, config.python.testsDir, `test_${kind}_${module}.py`);
  if (fs.existsSync(file)) return { file, contents: null, exists: true };
  return { file, contents: T.pythonTest({ kind, useCase }), exists: false };
}

/** A JSON case for an artifact gap in a doer that has no Python. */
function caseFor(config, skill, kind, target) {
  const id = `${kind}-covers-artifact`;
  const file = path.join(skill.dir, config.evals.dir, `${id}.json`);
  const body = {
    id,
    description: `${kind} check for ${target} — replace with the real assertion.`,
    type: 'contains',
    kind,
    covers: [target],
    file: 'SKILL.md',
    patterns: ['## Workflow'],
    provenance: `generated by gen-tests.mjs to close the ${kind} gap — make it assert something real`,
  };
  return { file, contents: JSON.stringify(body, null, 2) + '\n', exists: fs.existsSync(file) };
}

async function main(argv) {
  const yes = argv.includes('--yes') || argv.includes('-y');
  const only = argv.filter((a) => !a.startsWith('-'));
  const config = loadConfig();
  const skills = discoverSkills(config).filter((s) => only.length === 0 || only.includes(s.name));
  if (only.length && skills.length === 0) {
    console.error(`no such skill: ${only.join(', ')}`);
    return 1;
  }

  const prompter = new Prompter({ assumeYes: yes });
  let wrote = 0;
  let outstanding = 0;

  for (const skill of skills) {
    const { cases } = loadCases(config, skill.dir);
    const gaps = coverageGaps(config, skill, cases);
    if (gaps.length === 0) {
      console.log(`${green('PASS')} ${skill.name} ${dim('every artifact and module is covered')}`);
      continue;
    }

    console.log(`${yellow('GAPS')} ${bold(skill.name)}`);
    for (const gap of gaps) console.log(`  ${gap.kind.padEnd(11)} missing for ${gap.why} ${gap.target}`);

    if (only.length === 0) {
      outstanding += gaps.length;
      continue; // reporting mode: naming every gap in the repo, not writing files
    }

    const kinds = [...new Set(gaps.map((g) => g.kind))];
    for (const kind of kinds) {
      const kindGaps = gaps.filter((g) => g.kind === kind);
      const usePython = pythonModules(config, skill.dir).length > 0;
      const plan = usePython
        ? pythonTestFor(config, skill, kind)
        : caseFor(config, skill, kind, kindGaps.find((g) => g.why === 'artifact')?.target ?? kindGaps[0].target);

      const rel = path.relative(REPO_ROOT, plan.file);
      const targets = kindGaps.map((g) => g.target).join(', ');
      if (plan.exists) {
        console.log(`  ${yellow('skip')} ${rel} already exists — add ${kind} coverage for ${targets} inside it`);
        outstanding += 1;
        continue;
      }
      const ok = await prompter.confirm(`write:${rel}`, `  Write ${rel} to cover ${targets}?`, { default: true });
      if (!ok) {
        console.log(`  ${dim('left out')} ${rel}`);
        continue;
      }
      fs.mkdirSync(path.dirname(plan.file), { recursive: true });
      fs.writeFileSync(plan.file, plan.contents);
      console.log(`  ${green('wrote')} ${rel}`);
      wrote += 1;
    }
  }
  prompter.close();

  if (wrote) {
    console.log(bold(`\nWrote ${wrote} test file(s).`));
    console.log('Replace the placeholder expectations with the real ones, then: npm run check');
  }
  if (outstanding && only.length === 0) {
    console.log(dim(`\n${outstanding} gap(s). Close them with: npm run test:new -- <skill>`));
  }
  return outstanding && only.length === 0 ? 1 : 0;
}

if (import.meta.url === `file://${process.argv[1]}`) process.exit(await main(process.argv.slice(2)));
