#!/usr/bin/env node
// Fills the test gaps a skill has: for every artifact and every Python entrypoint
// that is missing an accuracy, edge-case, or performance test, generate one.
//
//   npm run test:new -- <skill>          # interactive: confirms each gap, then writes
//   npm run test:new -- <skill> --yes    # write everything missing, no questions
//   npm run test:new                     # report gaps across every skill
//
// Generated tests are scaffolds with real assertions in them — they run, and they
// fail honestly when the code is wrong. Replace the placeholder expectations with
// the real ones; that is the part only the author can do.
import fs from 'node:fs';
import path from 'node:path';
import { Prompter } from './lib/prompt.mjs';
import { activeArtifacts, coverageGaps, readManifest } from './lib/manifest.mjs';
import { hasPythonCode } from './lib/python.mjs';
import * as T from './lib/templates.mjs';
import { REPO_ROOT, discoverSkills, loadCases, loadConfig } from './lib/skills.mjs';
import { bold, dim, green, red, yellow } from './lib/report.mjs';

function gapsFor(config, skill) {
  const { manifest } = readManifest(config, skill.dir);
  if (!manifest) return { manifest: null, gaps: [] };
  const { cases } = loadCases(config, skill.dir);
  return { manifest, gaps: coverageGaps(config, skill.dir, manifest, cases) };
}

/** One Python test file per missing kind, covering everything that kind is missing. */
function pythonTestFor(config, skill, manifest, kind, targets) {
  const entrypoints = manifest.python?.entrypoints ?? [];
  if (entrypoints.length === 0) return null;
  const module = entrypoints[0].split('.')[0];
  const file = path.join(skill.dir, config.python.testsDir, `test_${kind}_${module}.py`);
  if (fs.existsSync(file)) return { file, contents: null, exists: true };
  const contents = T.pythonTest({
    kind,
    module,
    skillName: skill.name,
    covers: targets,
    entrypoints,
    artifacts: activeArtifacts(manifest),
  });
  return { file, contents, exists: false };
}

/** A JSON case for an artifact gap in a skill that has no Python. */
function caseFor(config, skill, kind, artifactIds) {
  const id = `${kind}-covers-artifacts`;
  const file = path.join(skill.dir, config.evals.dir, `${id}.json`);
  const body = {
    id,
    description: `${kind} check for ${artifactIds.join(', ')} — replace with the real assertion.`,
    type: 'contains',
    kind,
    covers: artifactIds,
    file: 'SKILL.md',
    patterns: ['## Workflow'],
    provenance: `generated by gen-tests.mjs to close the ${kind} gap — make it assert something real`,
  };
  return { file, contents: JSON.stringify(body, null, 2) + '\n', exists: fs.existsSync(file) };
}

async function main(argv) {
  const yes = argv.includes('--yes') || argv.includes('-y');
  const only = argv.filter((a) => !a.startsWith('-'));
  const config = loadConfig();
  const skills = discoverSkills(config).filter((s) => only.length === 0 || only.includes(s.name));
  if (only.length && skills.length === 0) {
    console.error(`no such skill: ${only.join(', ')}`);
    return 1;
  }

  const prompter = new Prompter({ assumeYes: yes });
  let wrote = 0;
  let outstanding = 0;

  for (const skill of skills) {
    const { manifest, gaps } = gapsFor(config, skill);
    if (!manifest) {
      console.log(`${red('FAIL')} ${skill.name} — no ${config.manifest.file}; run: npm run skill:new`);
      continue;
    }
    if (gaps.length === 0) {
      console.log(`${green('PASS')} ${skill.name} ${dim('every artifact and entrypoint is covered')}`);
      continue;
    }

    console.log(`${yellow('GAPS')} ${bold(skill.name)}`);
    for (const gap of gaps) console.log(`  ${gap.kind.padEnd(11)} missing for ${gap.why} ${gap.target}`);

    if (only.length === 0) {
      outstanding += gaps.length;
      continue; // reporting mode: naming every gap in the repo, not writing files
    }

    const byKind = new Map();
    for (const gap of gaps) {
      if (!byKind.has(gap.kind)) byKind.set(gap.kind, new Set());
      byKind.get(gap.kind).add(gap.target);
    }

    for (const [kind, targets] of byKind) {
      const list = [...targets];
      const usePython = hasPythonCode(config, skill.dir) && (manifest.python?.entrypoints ?? []).length > 0;
      const plan = usePython
        ? pythonTestFor(config, skill, manifest, kind, list)
        : caseFor(config, skill, kind, list.filter((t) => !t.includes('.')));

      if (!plan) continue;
      const rel = path.relative(REPO_ROOT, plan.file);
      if (plan.exists) {
        console.log(`  ${yellow('skip')} ${rel} already exists — add ${kind} coverage for ${list.join(', ')} inside it`);
        outstanding += 1;
        continue;
      }
      const ok = await prompter.confirm(`write:${rel}`, `  Write ${rel} to cover ${list.join(', ')}?`, { default: true });
      if (!ok) {
        console.log(`  ${dim('left out')} ${rel}`);
        continue;
      }
      fs.mkdirSync(path.dirname(plan.file), { recursive: true });
      fs.writeFileSync(plan.file, plan.contents);
      console.log(`  ${green('wrote')} ${rel}`);
      wrote += 1;
    }
  }
  prompter.close();

  if (wrote) {
    console.log(bold(`\nWrote ${wrote} test file(s).`));
    console.log('Replace the placeholder expectations with the real ones, then: npm run check');
  }
  if (outstanding && only.length === 0) {
    console.log(dim(`\n${outstanding} gap(s). Close them with: npm run test:new -- <skill>`));
  }
  return outstanding && only.length === 0 ? 1 : 0;
}

if (import.meta.url === `file://${process.argv[1]}`) process.exit(await main(process.argv.slice(2)));
