#!/usr/bin/env node
// Interactive skill generator. Asks the questions, then writes the whole skill:
// SKILL.md, skill.json, deterministic Python, accuracy/edge/performance tests,
// seed regression cases, and the interview record. Then validates and runs it.
//
//   npm run skill:new
//   npm run skill:new -- --answers answers.json --yes      # non-interactive
//   npm run skill:new -- --skip summary-brief              # generate all but this part
//
// Everything is generated by default. Leaving a part out is an option the author
// can take — never a question asked before the work starts.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { Prompter } from './lib/prompt.mjs';
import * as T from './lib/templates.mjs';
import { REPO_ROOT, loadConfig } from './lib/skills.mjs';
import { bold, dim, green, red, yellow } from './lib/report.mjs';

const KIND_BY_EXT = {
  '.csv': 'data', '.tsv': 'data', '.json': 'data', '.ndjson': 'data', '.parquet': 'data',
  '.md': 'report', '.txt': 'report', '.html': 'report', '.pdf': 'document', '.docx': 'document',
  '.png': 'chart', '.svg': 'chart', '.py': 'code', '.yaml': 'config', '.yml': 'config',
};

/** "summary-table: outputs/summary.csv — one row per category" */
export function parseArtifactLine(line) {
  const [head, ...restParts] = line.split(/\s+[—-]\s+/);
  const description = restParts.join(' - ').trim();
  const [rawId, rawPath] = head.split(':').map((s) => s?.trim());
  if (!rawId) return null;
  const id = rawId.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  const artifactPath = rawPath || `outputs/${id}.json`;
  return {
    id,
    path: artifactPath,
    kind: KIND_BY_EXT[path.extname(artifactPath).toLowerCase()] ?? 'data',
    description: description || `The ${id.replace(/-/g, ' ')} this skill produces.`,
  };
}

function parseArgs(argv) {
  const args = { skip: [], root: '.claude/skills' };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--answers') args.answersFile = argv[++i];
    else if (a === '--skip') args.skip.push(argv[++i]);
    else if (a === '--root') args.root = argv[++i];
    else if (a === '--yes' || a === '-y') args.yes = true;
    else if (a === '--no-verify') args.noVerify = true;
    else if (!a.startsWith('-')) args.name = a;
  }
  return args;
}

async function collect(prompter, args) {
  const kebab = (v) => /^[a-z0-9]+(-[a-z0-9]+)*$/.test(v);

  const name = await prompter.ask('name', 'What is the skill called? (lower-case-with-dashes)', {
    default: args.name ?? '',
    hint: 'The directory name and the name in SKILL.md. Say what it does, not what it is: "sales-summary", not "helper".',
    validate: (v) => (kebab(v) ? null : 'lower case letters, numbers and dashes only'),
  });

  const what = await prompter.ask('what', 'In one sentence, what does it do?', {
    hint: 'Third person: "Turns transaction rows into a per-category summary table and a short brief."',
    default: `Does the ${name.replace(/-/g, ' ')} job.`,
    validate: (v) => (v.length >= 20 ? null : 'a little more detail — this becomes the trigger description'),
  });

  const trigger = await prompter.ask('trigger', 'When should it fire? Finish: "Use when ..."', {
    hint: 'The words someone would actually type when they need it.',
    default: `Use when someone needs ${name.replace(/-/g, ' ')}.`,
    validate: (v) => (v.toLowerCase().startsWith('use when') ? null : 'start with "Use when"'),
  });

  const nonTrigger = await prompter.ask('nonTrigger', 'When must it NOT fire?', {
    hint: 'The near-miss request that should go somewhere else. This is what stops skills colliding later.',
    default: 'requests that only look similar but need a different skill',
  });

  const kind = await prompter.choose('kind', 'What kind of skill is it?', ['analysis', 'artifact', 'orchestration', 'utility'], {
    default: 'analysis',
  });

  const artifactLines = await prompter.list('artifacts', 'What files should it produce?', {
    hint: 'One per line: "summary-table: outputs/summary.csv — one row per category". Blank line if it produces none.',
  });
  const artifacts = artifactLines.map(parseArtifactLine).filter(Boolean);

  const wantsPython =
    kind === 'analysis'
      ? await prompter.confirm('python', 'Generate Python for the parts that must be exact (calculations, parsing, rules)?', { default: true })
      : await prompter.confirm('python', 'Does it need deterministic Python code?', { default: false });

  const steps = await prompter.list('steps', 'What are the steps, in order?', {
    hint: 'One per line, imperative: "Check the input columns". Blank line to finish. Leave empty for a sensible default.',
  });

  return { name, what, trigger, nonTrigger, kind, artifacts, wantsPython, steps };
}

function write(file, contents) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, contents);
  return file;
}

async function main(argv) {
  const args = parseArgs(argv);
  const config = loadConfig();
  const answers = args.answersFile ? JSON.parse(fs.readFileSync(args.answersFile, 'utf8')) : {};
  const prompter = new Prompter({ answers, assumeYes: args.yes });

  console.log(bold('\nNew skill\n'));
  console.log(dim('Answer as much as you can. Everything gets generated — docs, code, and all three kinds of test.\n'));

  const spec = await collect(prompter, args);
  prompter.close();

  const skillDir = path.resolve(REPO_ROOT, args.root, spec.name);
  if (fs.existsSync(skillDir)) {
    console.error(red(`\n${args.root}/${spec.name} already exists. Pick another name, or edit the existing skill.`));
    return 1;
  }

  const steps = spec.steps.length ? spec.steps : ['Check the input is what the skill expects', 'Do the work', 'Report what was produced'];
  const module = T.moduleNameFor(spec.name);
  const entrypoints = spec.wantsPython
    ? (spec.artifacts.length ? spec.artifacts : [{ id: spec.name }]).slice(0, 1).map((a) => `${module}.${T.functionNameFor(a.id)}`)
    : [];
  const python = spec.wantsPython ? { module, entrypoints } : null;

  const artifacts = spec.artifacts.map((a) =>
    args.skip.includes(a.id)
      ? { ...a, generate: false, skipReason: 'switched off at generation time with --skip' }
      : { ...a, producedBy: python ? `${module}.write_artifacts` : undefined },
  );

  const written = [];
  written.push(write(path.join(skillDir, 'SKILL.md'), T.skillMd({ ...spec, title: spec.name.replace(/-/g, ' ').replace(/^./, (c) => c.toUpperCase()), whatItDoes: spec.what, steps, artifacts, python })));
  written.push(
    write(
      path.join(skillDir, 'skill.json'),
      T.manifest({
        name: spec.name,
        kind: spec.kind,
        summary: spec.what,
        artifacts,
        python,
        skipped: args.skip,
      }),
    ),
  );
  written.push(write(path.join(skillDir, 'references/interview-notes.md'), T.interviewNotes({ name: spec.name, answers: prompter.transcript })));

  const active = artifacts.filter((a) => a.generate !== false);
  if (python) {
    written.push(write(path.join(skillDir, 'python', `${module}.py`), T.pythonModule({ module, skillName: spec.name, artifacts: active, entrypoints })));
    const covers = [...active.map((a) => a.id), ...entrypoints];
    for (const kind of config.coverage.kinds) {
      written.push(
        write(
          path.join(skillDir, 'python/tests', `test_${kind}_${module}.py`),
          T.pythonTest({ kind, module, skillName: spec.name, covers, entrypoints, artifacts: active }),
        ),
      );
    }
  }

  for (const seed of T.seedCases({ name: spec.name, artifacts: active, trigger: spec.trigger, nonTrigger: spec.nonTrigger })) {
    written.push(write(path.join(skillDir, config.evals.dir, seed.file), seed.text));
  }

  console.log(green(`\nGenerated ${written.length} files in ${path.relative(REPO_ROOT, skillDir)}/`));
  for (const file of written) console.log(dim(`  ${path.relative(REPO_ROOT, file)}`));

  if (!python && spec.kind === 'analysis') {
    console.log(yellow('\nNo Python was generated — anything this skill calculates will not be reproducible or testable.'));
  }
  if (args.skip.length) {
    console.log(yellow(`\nSkipped parts (recorded in skill.json with a reason): ${args.skip.join(', ')}`));
  } else if (active.length) {
    console.log(dim(`\nAll ${active.length} artifact(s) were generated. If you only wanted some of them, set "generate": false`));
    console.log(dim('with a "skipReason" in skill.json, or re-run with --skip <artifact-id>.'));
  }

  if (!args.noVerify) {
    console.log(bold('\nChecking what was generated...\n'));
    const run = (cmd, cmdArgs) => {
      try {
        console.log(execFileSync(cmd, cmdArgs, { cwd: REPO_ROOT, encoding: 'utf8', env: { ...process.env, NO_COLOR: '1' } }));
        return true;
      } catch (err) {
        console.log(`${err.stdout ?? ''}${err.stderr ?? ''}`);
        return false;
      }
    };
    run('node', ['scripts/validate-skill.mjs', spec.name]);
    run('node', ['scripts/run-regression.mjs', spec.name]);
  }

  console.log(bold('\nNext'));
  console.log(`  1. Open ${path.relative(REPO_ROOT, path.join(skillDir, 'SKILL.md'))} and replace the scaffolded parts with the real procedure.`);
  if (python) console.log(`  2. Implement ${path.relative(REPO_ROOT, path.join(skillDir, 'python', `${module}.py`))}, then make its three test files assert the real behaviour.`);
  console.log(`  ${python ? 3 : 2}. Run it on a real task, then fold what you learn back in as an edit AND a test.`);
  console.log(`  ${python ? 4 : 3}. npm run check    ${dim('(then: npm run save)')}`);
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) process.exit(await main(process.argv.slice(2)));
